### ISSUE TITLE
Last line of config gets ignored if it doesn't end with newline character

### ISSUE THREAD

**Issue by SunnDealer** [x42/midimap.lv2#3] opened 2022-01-07 18:03 UTC
Hi.
The last line of configuration file gets ignored if it doesn't end with newline character. I encountered this problem because I use midimap with Carla and it trims config before passing it to the plugin.
Here's the problematic line: https://github.com/x42/midimap.lv2/blob/063abf4fadf786c58a4d5cd4e3a638a5c7f9e9d3/src/midimap.c#L1024
`strchr` will return `NULL` even if there are some unparsed characters left.

Link to issue in Carla: https://github.com/falkTX/Carla/issues/1521

**Comment by x42** [comment] 2022-01-07 20:47
Thanks for bringing this issue to our attention.

This is however tricky. Unix text config files usually do have a newline at the end of each line.
Most text editors warn about this, e.g. vim shows "no newline at end of file".

I'm wary of introducing host-specific work-arounds and argue that the issue is in Carla, it should treat state as opaque data "LV2_STATE_IS_POD" (plain old data), and not modify it, like other LV2 hosts do.

I'll check with @falktx, and only if Carla cannot or won't address this, adapt the parser.

**Comment by falkTX** [comment] 2022-01-07 20:48
A PR is open against Carla to fix this, I will adapt it a bit and merge, to ensure state is consistent.

**Comment by x42** [comment] 2022-01-07 20:52
Great news.
Thanks for the quick reply. I'll close this issue here, then

**Closed as completed by x42** 2022-01-07 20:52 UTC
